annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 3.3.1
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: Apache Spark is a high-performance engine for large-scale computing tasks, such as data processing, machine learning and real-time data streaming. It includes APIs for Java, Python, Scala and R.
engine: gotpl
home: https://github.com/bitnami/charts/tree/main/bitnami/spark
icon: https://bitnami.com/assets/stacks/spark/img/spark-stack-220x234.png
keywords:
  - apache
  - spark
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: spark
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/spark
  - https://spark.apache.org/
version: 6.3.12